[package]
name = "SplitMoneyManager"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.32.1", features = ["bundled"] }
argon2 = "0.5"
password-hash = "0.5"
regex = "1.10"
rand_core = { version = "0.6", features = ["std"] }
eframe = "0.30"
egui = "0.30"